# Generated by Django 2.0.7 on 2018-07-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='quote_text',
        ),
    ]
