# Generated by Django 2.0.7 on 2018-07-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0003_auto_20180725_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='favouriting_users',
            new_name='favoriting_users',
        ),
    ]
